### ISSUE TITLE
lxmlx installation error

### ISSUE THREAD

**Issue by ArtJaspa** [innodatalabs/lxmlx#5]
Hi Mike!

I installed lxmlx on my PC, no error prompted on attached log file. But when test*.py where run, below is the error prompted:

Traceback (most recent call last):
  File "E:\Program Files\Python34\Lib\lxmlx\test\test_event.py", line 4, in <module>
    import lxml.etree as et
ImportError: No module named 'lxml.etree'

Please advise.

Regards,
Art

[lxmlx.log](https://github.com/innodatalabs/lxmlx/files/1766076/lxmlx.log)

**Comment by mkroutikov** [comment]
Hi Art,

You should be able to install it with:
```
pip install lxmlx
```
That would automatically install the required dependencies.

If you install from the source instead, please install required packaged explicitly:

```
pip install -r requirements.txt
```

**Comment by mkroutikov** [comment]
I updated [`README.md`](https://github.com/innodatalabs/lxmlx) to add instructions for building and testing this package.

**Comment by ArtJaspa** [comment]
Thanks, Mike. Below work best for me on all modules with installation problem:

python -m pip **--trusted-host pypi.python.org** lxmlx

![image](https://user-images.githubusercontent.com/14936802/37088892-bd35bd64-2239-11e8-9150-dd1bde859ad3.png)

**Comment by mkroutikov** [comment]
Great!

You should also have `pip` script in `Python34\Scripts\pip`, and do the same like this:
```
E:\Program Files\Python34\Scripts\pip install lxmlx
```

If you use virtual environemnt for your project, `pip` is installed in virtual environment and use is even simpler:
```
pip install lxmlx
```
